spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/logistics?useUnicode=true&characterEncoding=utf-8
    data-username: root
    password: 123456
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  redis:
    port: 6379
    host: localhost
mybatis:
  mapper-locations: classpath:mapper/**.xml
logging:
  level:
    logistics.logistics:
    debug
